### ISSUE TITLE
Container support

### ISSUE THREAD

**Issue by jsuttonnc** [dxFeed/dxfeed-graal-net-api#40]
I have built a small .NET worker service that executes every x seconds and pulls some quotes.  Running from the development environment works great.  When I publish it and try running it from a local docker container, it is failing with the following error.  Does the library not support containerization?

Unhandled exception. System.DllNotFoundException: Unable to load shared library 'DxFeedGraalNativeApi' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/app/DxFeedGraalNativeApi.so: cannot open shared object file: No such file or directory
/app/libDxFeedGraalNativeApi.so: cannot open shared object file: No such file or directory
/app/DxFeedGraalNativeApi: cannot open shared object file: No such file or directory
/app/libDxFeedGraalNativeApi: cannot open shared object file: No such file or directory
   at DxFeed.Graal.Net.Native.Graal.Isolate.GraalCreateIsolate(IntPtr param, IntPtr& isolate, IntPtr& isolateThread)
   at DxFeed.Graal.Net.Native.Graal.Isolate.CreateIsolate()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at DxFeed.Graal.Net.Native.Graal.Isolate.get_Instance()
   at DxFeed.Graal.Net.Native.Graal.IsolateThread.<>c.<.cctor>b__13_0()
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at DxFeed.Graal.Net.Native.Graal.IsolateThread.get_CurrentThread()
   at DxFeed.Graal.Net.Native.Graal.Isolate.get_CurrentThread()
   at DxFeed.Graal.Net.Native.Endpoint.Handles.BuilderSafeHandle.Create()
   at DxFeed.Graal.Net.Native.Endpoint.BuilderNative.Create()
   at DxFeed.Graal.Net.Api.DXEndpoint.Builder.Build()
   at DxFeed.Graal.Net.Api.DXEndpoint.Create(Role role)
   at DxFeed.Graal.Net.Api.DXEndpoint.Create()
   at DxFeedService.Workers.TradeWorker.GetNewSubscription()

**Comment by stdcion** [comment]
@jsuttonnc hello!

Could you please provide your Makefile for Docker? Are you running this in a Linux container? In general, there should be no restrictions for working in a container. 

Best regards,
dxFeed APIs Team

**Comment by jsuttonnc** [comment]
I'm not using a makefile.  I'm using the built in docker support found in .NET 7.  I'm publishing to a Linux container.

https://learn.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows

**Comment by stdcion** [comment]
Sorry, I mean Dockerfile. What did you specify in the FROM section? Are you sure you copied DxFeedGraalNativeApi.so into the container?

**Comment by stdcion** [comment]
If you are using alpine linux, at the moment gcompat (glibc compatibility layer) for musl is required. Installation on alpine linux `apk update && apk add gcompat libstdc++`.
