### ISSUE TITLE
Version 1.3.0 Error: com.dxfeed.event.candle.CandleSymbol cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by EcBen** [dxFeed/dxfeed-graal-net-api#55]
@stdcion 
Testing out the new 1.3.0 version and getting this error:
```
SendCandleSubscription() for /ESM24:XCME{=m}{fromTime=20240519-151501.000}
SendCandleSubscription() Error: DxFeed.Graal.Net.Native.ErrorHandling.JavaException: Java exception of type 'java.lang.ClassCastException' was thrown. com.dxfeed.event.candle.CandleSymbol cannot be cast to java.lang.String
        at com.dxfeed.event.market.MarketEventDelegateSet.getTimeSeriesDelegatesByEventSymbol(MarketEventDelegateSet.java:51)
        at com.dxfeed.api.impl.DXFeedImpl.toSubscription(DXFeedImpl.java:541)
        at com.dxfeed.api.impl.DXFeedImpl.access$800(DXFeedImpl.java:63)
        at com.dxfeed.api.impl.DXFeedImpl$SubscriptionChangeListener.symbolsAdded(DXFeedImpl.java:737)
        at com.dxfeed.api.DXFeedSubscription.addSymbolImpl(DXFeedSubscription.java:783)
        at com.dxfeed.api.DXFeedSubscription.addSymbols(DXFeedSubscription.java:507)
        at com.dxfeed.sdk.subscription.SubscriptionNative.dxfg_DXFeedSubscription_addSymbol(SubscriptionNative.java:104)
   at DxFeed.Graal.Net.Native.ErrorHandling.JavaExceptionHandle.ThrowException()
   at DxFeed.Graal.Net.Native.ErrorHandling.JavaExceptionHandle.ThrowIfJavaThreadExceptionExists()
   at DxFeed.Graal.Net.Native.ErrorHandling.ErrorCheck.ThrowIfJavaThreadExceptionExists()
   at DxFeed.Graal.Net.Native.ErrorHandling.ErrorCheck.SafeCall(Int32 result)
   at DxFeed.Graal.Net.Native.Subscription.SubscriptionNative.SubscriptionImport.AddSymbol(IntPtr thread, SubscriptionHandle* subHandle, Object symbol)
   at DxFeed.Graal.Net.Native.Subscription.SubscriptionNative.AddSymbols(Object[] symbols)
   at DxFeed.Graal.Net.Api.DXFeedSubscription.AddSymbols(Object[] symbols)
```

Has something changed with how Candle subscriptions work?

**Comment by stdcion** [comment]
Hello @EcBen 

Сould you please show a sample code? How did you create and add the symbol?

**Comment by stdcion** [comment]
Okay, I get it, apparently you have some other market event in the same subscription in addition to Candle, say it's a Quote. In this case, there will indeed be an exception.

```csharp
    public static async Task Main(string[] args)
    {
        var endpoint = DXEndpoint.Create().Connect("demo.dxfeed.com:7300");
        var sub = endpoint.GetFeed().CreateSubscription(typeof(Candle), typeof(Quote));

        sub.AddEventListener(events =>
        {
            foreach (var candle in events)
            {
                Console.WriteLine(candle);
            }
        });
        var s = new TimeSeriesSubscriptionSymbol(CandleSymbol.ValueOf("/ESM24:XCME", CandlePeriod.ValueOf(1, CandleType.Minute)), TimeFormat.Default.Parse("20240519-151501"));
        var s1 = new TimeSeriesSubscriptionSymbol("/ESM24:XCME{=m}", TimeFormat.Default.Parse("20240519-151501"));
        sub.AddSymbols(s, s1);

        await Task.Delay(Timeout.Infinite);
    }
```

So our recommendation is to separate subscriptions with Candle, from other market events. 

This is because the semantics of the symbols for Candle are different from other market events.  So if you add say the `AAPL ` symbol to a subscription that contains Candle and Quote, it will not work for Candle but will work for Quote, and vice versa, the `AAPL{=m}` symbol will work for Candle but not for Quote, but all these symbols will be added to the subscriptions matrix, which can have a negative impact.

**Comment by EcBen** [comment]
@stdcion Thanks for looking into this.
Yes, we are subscribing to both Candles and Quotes. So if we subscribe to `AAPL`, the Quotes and tick by tick Candles will stream in for `AAPL`, then we're subscribing to `AAPL{=m}` to get 1 Minute Candles.

> So our recommendation is to separate subscriptions with Candle, from other market events.

How do we separate the subscriptions? 

We create the subscription at the same time and have 2 event handlers registered:
```csharp
var eventTypes = new Type[]
{
  typeof(Quote),
  typeof(Candle)
};

_subscriptions = _endpoint.GetFeed().CreateSubscription(eventTypes);
_subscriptions.AddEventListener(OnMarketDataEventsAsync);
_subscriptions.AddEventListener(OnMarketDataEventsGetOneOffQuote);
```

When calling `AddSymbols(...)`, we're only including one symbol at a time:
```csharp
var timeSeriesSymbol = new TimeSeriesSubscriptionSymbol(candleSymbol, dateTime); // AAPL{=m}
_subscriptions.AddSymbols(timeSeriesSymbol);
...
var symbols = new string[1]
{
    symbol // AAPL
};
_subscriptions.AddSymbols(symbols);
```

Can the call to `CreateSubscription()` be made twice? Once for the `typeof(Quote)` and once for the `typeof(Candle)`?

**Comment by stdcion** [comment]
Yes, you can create two subscriptions, separately for Quote and separately for Candle.
For example:

```csharp
    public static async Task Main(string[] args)
    {
        var endpoint = DXEndpoint.Create().Connect("demo.dxfeed.com:7300");

        var candleSub = endpoint.GetFeed().CreateSubscription(typeof(Candle));
        candleSub.AddEventListener(events =>
        {
            foreach (var candle in events)
            {
                Console.WriteLine(candle);
            }
        });
        candleSub.AddSymbols(new TimeSeriesSubscriptionSymbol("AAPL{=m}", TimeFormat.Default.Parse("20240519-151501")));

        var quoteSub = endpoint.GetFeed().CreateSubscription(typeof(Quote));
        quoteSub.AddEventListener(events =>
        {
            foreach (var candle in events)
            {
                Console.WriteLine(candle);
            }
        });
        quoteSub.AddSymbols("AAPL");


        await Task.Delay(Timeout.Infinite);
    }
```

**Comment by EcBen** [comment]
Thanks! We'll give that a try.
